# Optimized development environment
# Usage: docker-compose -f docker-compose.dev.yml up
version: '3.8'

services:
  client:
    build:
      context: ./web-app
      dockerfile: client/Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      # Live code mounting - instant updates
      - ./web-app/client/src:/app/src
      - ./web-app/client/public:/app/public
      - ./web-app/client/index.html:/app/index.html
      - ./web-app/client/vite.config.ts:/app/vite.config.ts
      - ./web-app/client/tailwind.config.js:/app/tailwind.config.js
      - ./web-app/client/postcss.config.js:/app/postcss.config.js
      - ./web-app/client/tsconfig.json:/app/tsconfig.json
      - ./web-app/client/tsconfig.node.json:/app/tsconfig.node.json
      # Shared types
      - ./web-app/shared:/shared
      # Exclude node_modules from host (container version takes precedence)
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
      - VITE_WS_URL=ws://localhost:3001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - server
    networks:
      - dns-bench-network
    stdin_open: true
    tty: true
    restart: unless-stopped

  server:
    build:
      context: ./web-app
      dockerfile: server/Dockerfile
      target: development
    ports:
      - "3001:3001"
    volumes:
      # Live code mounting - instant updates
      - ./web-app/server/src:/app/src
      - ./web-app/server/tsconfig.json:/app/tsconfig.json
      - ./web-app/server/local-dns.json:/app/local-dns.json
      - ./web-app/server/public-dns.json:/app/public-dns.json
      # Shared types
      - ./web-app/shared:/shared
      # Data persistence
      - ./data:/app/data
      # Exclude node_modules from host
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CORS_ORIGIN=http://localhost:3000
      - DB_PATH=/app/data/dns-bench.db
      - HOST_IP=${HOST_IP:-}
      - DOCKER_HOST_IP=${HOST_IP:-}
      - TSX_WATCH=true
    networks:
      - dns-bench-network
    cap_add:
      - NET_RAW
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dns-bench-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  redis_data:

networks:
  dns-bench-network:
    driver: bridge